export const professions = [
  "Accounting technician",

  "Aid worker/humanitarian worker",

  "Animator",
  "Archaeologist",

  "Auditor",
  "Automotive engineer",

  "Brand manager",
  "Broadcasting presenter",

  "Clothing and textile technologist",
  "Colour technologist",
  "Computer sales support",

  "Cyber security specialist",
  "Data analyst",
  "Data scientist",
  "Data visualisation analyst",
  "Database administrator",

  "Dentist",
  "Design engineer",
  "Dietitian",
  "Diplomatic service",
  "Doctor (general practitioner, GP)",
  "Doctor (hospital)",
  "Dramatherapist",
  "Economist",
  "Editorial assistant",

  "Equal opportunities officer",

  "Forensic scientist",
  "Geneticist",
  "Geographical information systems manager",

  "Human resources officer",
  "Hydrologist",
  "Illustrator",

  "Journalist",
  "Laboratory technician",

  "Logistics/distribution manager",
  "Magazine features editor",

  "Paramedic",
  "Patent attorney",
  "Patent examiner",
  "Pension scheme manager",
  "Personal assistant",

  "QA analyst",
  "Quality assurance manager",

  "Secretary",
  "Software developer",
  "Soil scientist",
  "Systems analyst",
  "Systems developer",
  "Tax inspector",
  "Teacher (nursery/early years)",
  "Technical author",
  "Technical sales engineer",
  "Television production assistant",
  "UX designer",
  "Veterinary surgeon",
  "Video game designer",
  "Video game developer",
  "Water engineer",
  "Web designer",
  "Web developer",
  "Youth worker",
];

export const skills = [
  "Algorithms",
  "Analytical Skills",
  "Big Data",
  "Calculating",
  "Compiling Statistics",
  "Data Analytics",
  "Data Mining",
  "Database Design",
  "Database Management",
  "Documentation",
  "Modeling",
  "Modification",
  "Needs Analysis",
  "Quantitative Research",
  "Quantitative Reports",
  "Statistical Analysis",
  "Applications",
  "Certifications",
  "Coding",
  "Computing",
  "Configuration",
  "Customer Support",
  "Debugging",
  "Design",
  "Development",
  "Hardware",
  "Implementation",
  "Information Technology",
  "Infrastructure",
  "Languages",
  "Maintenance",
  "Network Architecture",
  "Network Security",
  "Networking",
  "New Technologies",
  "Operating Systems",
  "Programming",
  "Restoration",
  "Security",
  "Servers",
  "Software",
  "Solution Delivery",
  "Storage",
  "Structures",
  "Systems Analysis",
  "Technical Support",
  "Technology",
  "Testing",
  "Tools",
  "Training",
  "Troubleshooting",
  "Usability",
  "Benchmarking",
  "Budget Planning",
  "Engineering",
  "Fabrication",
  "Following Specifications",
  "Operations",
  "Performance Review",
  "Project Planning",
  "Quality Assurance",
  "Quality Control",
  "Scheduling",
  "Task Delegation",
  "Task Management",
  "Blogging",
  "Digital Photography",
  "Digital Media",
  "Facebook",
  "Instagram",
  "Networking",
  "Pinterest",
  "SEO",
  "Social Media Platforms",
  "Twitter",
  "Web Analytics",
  "Client Relations",
  "Email",
  "Requirements Gathering",
  "Research",
  "Subject Matter Experts (SMEs)",
  "Technical Documentation",
];
